### ISSUE TITLE
Add WalletConnect Provider

### ISSUE THREAD

**Issue by jettblu** [CMU-Blockchain-Club/dappStarter#1]
**Prize** 
$50

**Description** 

Add the ability to connect a wallet via WalletConnect. This will require the following steps:

1.  Add a WalletConnect option on the [connect page](https://github.com/CMU-Blockchain-Club/dappStarter/blob/main/pages/profile/connect.tsx)
2.  Add a QR code popup when the user selects the option. Scanning the code will allow users to connect their mobile wallet
3. Update the [IWallet interface](https://github.com/CMU-Blockchain-Club/dappStarter/blob/main/models/IWallet.ts) with the returned provider object

Whenever, the dapp makes a transaction request, the WalletConnect provider will automatically ask for approval on the user's device. For more information, visit the [WalletConnect Docs](https://docs.walletconnect.com/quick-start/dapps/web3-provider).

**Submission** 
To receive the prize, please fork this repository and submit a pull request when updated. When done, comment on this issue with a reference to your changes and your Ethereum wallet address.

**Comment by NavidK27** [comment]
Hey! I created a pull request with the changes. The commit IDs are:
1) 67562215e5e768e35a7d40a725c8a853ec9665d6
2) b1eecf1cb6b7cd032b58263c5383df3b23230449
3) 22823a3667820c9e5ba6bb145d093dd9ddeadbef
The Ethereum address is: 0x669617833b03a216577b9fe12f8260d38543fab6

**Comment by jettblu** [comment]
Thanks! The PR is under review.

**Comment by jettblu** [comment]
Hey Navid, your pull request has been accepted! You code is well written and the connection works great. I added client metadata as well, so users can learn more about the app they are connecting to. 

You will receive $50 of DAI on the Arbitrum network by tonight.
